project:
  type: website
  output-dir: docs


# website settings
website:
  title: "Jan Pfänder"                                # Your name
  image: images/profile.jpg
  
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    # your sub-pages
    left:
      - text: "Research"
        href: research/index.qmd
      - text: "CV"
        href: cv/index.qmd
        
    # your social media handles
    right:
      - icon: github
        href: https://github.com/janpfa
      - icon: twitter
        href: https://twitter.com/janpfaender
      - icon: envelope
        aria-label: email
        href: "mailto:janlukas.pfaender@gmail.com" 
        
  page-footer: 
    background: light
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Jan Pfänder</span>
      
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>, 
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

